name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
      
      - name: Build binary
        run: |
          cd zed-auto-updater
          cargo build --release
      
      - name: Rename executable
        run: |
          cd zed-auto-updater/target/release
          copy zed-auto-updater.exe zed-windows-auto-updater.exe
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./zed-auto-updater/target/release/zed-windows-auto-updater.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}